name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release (e.g., 1.0.0)'
        required: true

      releaseNotes:
        description: Provide release notes for following release
        required: false
        default: ''
permissions:
  contents: write

jobs:
  check-tag:
    name: Checking tag existence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - name: Check for Tag
        run: |
          TAG="v${{inputs.version}}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} exists"
            exit 1;
          else
            echo "Tag ${TAG} does not exist"
          fi

  release:
    needs: check-tag
    if: ${{ github.ref_name == 'main' }}
    name: Create Release and Update Version
    runs-on: ubuntu-latest
    outputs:
      newSHA: ${{steps.sha.outputs.new_sha}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Bump release version
        id: bump_version
        run: |
          echo "Testing release ${{ inputs.version }}" >> README.md
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Commit version changes
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.version }}

          echo "Setting version to $NEW_VERSION"

          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore: bump version to $NEW_VERSION"
          git tag $NEW_VERSION

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: get SHA
        id: sha
        run: |
          echo "new_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git checkout -b release/${{ steps.bump_version.outputs.version }}

      - name: Push new branch
        run: |
          git push origin release/${{ steps.bump_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: elgohr/Github-Release-Action@10548946591
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ steps.bump_version.outputs.version }}
          tag: v${{ steps.bump_version.outputs.version }}
          body: |
            Release notes for version ${{ steps.bump_version.outputs.version }}

            ${{ inputs.releaseNotes }}

      - name: Checkout to main
        run: |
          git switch main

  after-release:
    needs: release
    if: ${{ github.ref_name == 'main' }}
    name: Prepare main branch for development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
          ref: ${{ needs.release.outputs.newSHA }}

      - name: Bump snapshot version
        id: bump_version
        run: |
          echo "Setting snapshot version ${{ inputs.version }}-snapshot" >> README.md
          echo "version=${{ inputs.version }}-snapshot" >> $GITHUB_OUTPUT

      - name: Commit version changes
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.version }}

          echo "Setting development to $NEW_VERSION"

          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore: bump development to $NEW_VERSION"

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}